### PR TITLE
API should return bagnowka images urls directed to AWS  (new)

### PR DESCRIPTION
**Pull request by Libisch**
(#165 updated)
**Overview**
- All DBSs images (from bhp) are stored in google storage, and the API returned `main_image_url` to gcs. 
- New photoUnits will be added to BH DBS from external sources, starting scraped images from "www.bagnowka.pl" images.  
- Bagnowka images are stored in AWS
- in order to get the correct URLs for the images stored in AWS s3, the API should identify these items, and set the `main_image_url` and `thumbnail_url` to direct to AWS, instead of the default gcs storage.

(See #146)

**Applied Changes** 
- Updated **item.py**: changed `enrich_item` to identify bagnowka images and return correct `main_image_url` and `thumbnail_url` - now leading to AWS s3.
- Updated **v1_endpoints.py** `@v1_endpoints.route('/search')` to show error log messages.
- Added AWS bucket to **app_server.yaml**

### CODE REVIEW

**Comment by Libisch** [comment]
@TheGrandVizier yours to QA

**Comment by OriHoch** [comment]
@Libisch  - please write what you would like @TheGrandVizier to test, currently it's not clear
also, did you migrate the bagnowka images to test environment? if not, then it can't be tested (except maybe regression tests)

**Comment by Libisch** [comment]
* @OriHoch For items migration we need to execute [this](https://github.com/Beit-Hatfutsot/dbs-back/issues/132#issuecomment-299098927) (maybe tomorrow?).
* @TheGrandVizier We'll wait for the front [#351](https://github.com/Beit-Hatfutsot/dbs-front/issues/351) and then you'll be able to test it. I'll Update you when it's ready.


Expected behavior for future QA: On both search results and item page, API response should contain `main_image_url` and `thumbnail_url` according to source: 
- If an item has a `"bagnowka": "True"` field, the image url should be `https://s3-us-west-2.amazonaws.com/bagnowka-scraped/full/{PICTURE ID}.jpg`. 
- Otherwise, it should be `https://storage.googleapis.com/{BUCKET}/{PICTURE ID}.jpg`

**Comment by OriHoch** [comment]
I updated the release notes and assigned #169 to you - to run it tomorrow (we can do it together)

**Comment by OriHoch** [comment]
@Libisch regarding you testing notes - they will be lost here in the pull request
better to put it in an open issue which you will assign to @TheGrandVizier when it's ready for QA
it could be an issue specifically for this task
`[Task] should test Bagnowka after frontend is ready`
and write all details there

**Pull request merged**
